In [1]:
#Create a 3*3 array of non-zero elements and replace the first row to all zeros.
import numpy as np
arr= np.arange(0,9)
arr=arr.reshape(3,3)
#print(arr)
for i in range(0,3):
    arr[0][i]=0
print(arr)
    
    



In [22]:
# 2) Create a 4 by 4 array from 1 to 16. Extract the last two rows.
import numpy as np
arr = np.arange(0, 16)
arr = arr.reshape(4, 4)
g = []
print(arr)
for i in range(2, 4):
    for j in range(0, 4):

        g.append(arr[i][j])
arr3 = np.array(g)
arr3 = arr3.reshape(2, 4)
print(arr3)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 8  9 10 11]
 [12 13 14 15]]









6) Create a 3*3 array and multiply the elements of first column by 10, second column by 20 and third column by 30.

In [19]:
#3) Create and multiply two 2-dimenesional array and print the result
import numpy as np
arr1 = np.arange(0, 16)
arr1 = arr1.reshape(4, 4)
arr2 = np.arange(0, 16)
arr2 = arr2.reshape(4, 4)
print(arr1,"\n")
print(arr2,"\n")
print(arr1*arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]
 [144 169 196 225]]


In [27]:
#4) Generate random 3*3 array and find sum of all the elements
import numpy as np
arr=np.random.randint(9,size=(3,3))
print(arr)
sum=0
for i in range(0,3):
    for j in range(0,3):
        sum=sum+arr[i][j]

#print(arr.sum())
print(sum)


[[0 5 3]
 [7 6 8]
 [8 3 5]]
45
45


In [28]:
#5) Find transpose of a matrix
import numpy as np
arr= np.arange(0,9)
arr=arr.reshape(3,3)
print(arr)
print(arr.transpose())

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [31]:
#6) Create a 3*3 array and multiply the elements of first column by 10, second column by 20 and third column by 30.
import numpy as np
arr=np.random.randint(9,size=(3,3))
print(arr)

for i in range(0,3):
    for j in range(0,3):
        if(i==0):
            arr[i][j]=arr[i][j]*10
        elif(i==1):
            arr[i][j]=arr[i][j]*20
        else:
            arr[i][j]=arr[i][j]*30


print(arr)


[[8 3 7]
 [0 7 8]
 [8 5 6]]
[[ 80  30  70]
 [  0 140 160]
 [240 150 180]]
